# Boss直聘网页元素定位器 (zhipin.com)
LOGIN_BTN = "//li[@class='nav-figure']"
LOGIN_SCAN_SWITCH = "div.btn-sign-switch.ewm-switch"
USER_AVATAR_OR_MENU = "a.header-user"
JOB_LIST_CONTAINER = "div.job-list-container"
JOB_CARD_BOX = "li.job-card-box"
JOB_LIST_SELECTOR = "ul.job-list-box > li.job-card-box"
JOB_NAME_LINK = "a.job-name"
COMPANY_NAME_TEXT = "div.company-info h3.company-name a"
JOB_AREA_TEXT = "span.job-area"
TAG_LIST_ITEMS = "ul.tag-list li"
CHAT_BUTTON = "a.btn-startchat"
ERROR_CONTENT_TEXT = "div.error-content"
JOB_DETAIL_SALARY_TEXT = "div.info-primary span.salary"
RECRUITER_INFO_TEXT = "div.job-boss-info div.name"
HR_ACTIVE_TIME_TEXT = "span.boss-active-time"
JOB_DESCRIPTION_TEXT = "div.job-detail-section div.job-sec-text"
DIALOG_TITLE_TEXT = "div.dialog-title"
DIALOG_CLOSE_BUTTON = "i.icon-close"
CHAT_INPUT_TEXTAREA = "textarea#chat-input"
DIALOG_CONTAINER_DIV = "div.dialog-container"
SEND_BUTTON_ACTION = "button.btn-send"
IMAGE_UPLOAD_INPUT = "div[aria-label='发送图片'] input[type='file']"
DIALOG_CONTENT_DIV = "div.dialog-con"
CHAT_LIST_ITEM_SELECTOR = "ul.chat-list li.chat-item"
COMPANY_NAME_IN_CHAT_TEXT = "div.chat-info div.name"
LAST_MESSAGE_TEXT = "span.last-msg-text"
FINISHED_TEXT_DIV = "div.load-more-text.finished"
QR_CODE_LOGIN_TAB = "div.sign-tab-item[data-tab='qrcode']"
QR_CODE_IMAGE = "div.qrcode-img img"
LOGIN_TIMEOUT_MESSAGE = "div.qrcode-tip.error"
NO_MORE_JOBS_TEXT = "div.job-list-bottom-text.finished"
print("Boss Locators defined.")
